id: P000822
initial_creation_type: ebook
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmps7elhw0z.jpg
  credit: tmpjvtmsmn1.jpg
